# Generated by Django 2.2.4 on 2019-10-02 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_products_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
